#library(pheatmap)
#pdf("Rplots.pdf",width = 6, height = 15)
#png("heatCluster.png", type="cairo-png")
#pdf("heatCluster.pdf",width = 6, height = 15)
attach(mtcars)
opar <- par(no.readonly=T)
#par(pin=c(1,1))
#par(mfrow=c(2,2))
layout(matrix(c(1,1,2,2,3,4),3,2,byrow=T),widths=c(2,1),heights=c(1,1,1))
plot(mtcars$wt,mtcars$mpg,xlab="car",ylab="mail")
hist(wt)
hist(mpg)
hist(disp)
par(opar)
detach(mtcars)